config/routes.rb
DemoApp::Application.routes.draw do

 
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about' 
  match '/signup',  :to => 'users#new'
  match '/signin',  :to  => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  root :to => 'pages#home'
  
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)

end

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1><%= @title %></h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>OAuth 2.0</h1>
    <p>Integrare servizi come Facebook e Twitter in un progetto Rails</p>

    <p style="text-align: center; margin: 50px 0px;">
    	<%= link_to "Accedi", signin_path, class: "btn btn-large btn-success" %>
    </p>
    <p style="text-align: center;">
    	<a href="signup?provider=twitter" class="btn btn-large btn-info" >Iscriviti con twitter</a>
		<a href="signup?provider=facebook" class="btn btn-large btn-primary">Iscriviti con facebook</a>    
    </p>                       
                                                        
  </div>
<% end %> 