config/routes.rb
DemoApp::Application.routes.draw do

 
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about' 
  match '/signup',  :to => 'users#new'
  match '/signin',  :to  => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  root :to => 'pages#home'
  
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)

end

app/views/layouts/_header.html.erb
<header> 
        <nav class="round">
          <ul>
            <!-- <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Users",users_path %></li> -->
            
            <% if signed_in? %>
 				<li><%= link_to "Profile", user_path(current_user) %></li>
 				<li><%= link_to "Settings",edit_user_path(current_user)%>
 				<li><%= link_to "Sign out", signout_path, :method => "delete" %></li> 
 			<% end %>	       
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title> 
  <%= render '/layouts/stylesheets'%>
</head>
<body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= render '/layouts/header'%>
      <section class="round">
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </section>
    </div>
  </body>
</html>